version: 0.1
phases:
  install:
    runtime_versions:
      nodejs: 12
    commands:
      - 'touch .npmignore'
  pre_build:
    commands:
      - 'npm install'
  build:
    commands:
      - 'npm run build'
artifacts:
  base-directory: dist
  files:
    - '**/*'